export const roomMapPositions = Object.freeze({
  entrance: { x: 7.5, y: 27 },
  'stone-court': { x: 20.5, y: 25 },
  'old-altar': { x: 22.3, y: 10 },
  'broken-bridge': { x: 34, y: 20 },
  'bronze-moon-room': { x: 46, y: 20 },
  'supply-alcove': { x: 23, y: 40 },
  'mechanism-path': { x: 36.5, y: 32 },
  'stone-gate': { x: 36.5, y: 41 },
  'stone-camp': { x: 34, y: 66 },
  'moon-corridor': { x: 34, y: 57 },
  'moon-secret-room': { x: 22, y: 58 },
  'hidden-chest-room': { x: 23, y: 70 },
  'sand-pit': { x: 50, y: 56 },
  'echo-hall': { x: 63, y: 55 },
  'merchant-bones': { x: 33.5, y: 69 },
  'drain-path': { x: 47, y: 65 },
  'star-altar': { x: 45.5, y: 74 },
  'moon-gate': { x: 62, y: 64 },
  'corridor-camp': { x: 52, y: 72 },
  'throne-antechamber': { x: 58.5, y: 81 },
  'star-side-hall': { x: 50, y: 82 },
  'ancient-coffer': { x: 53, y: 92 },
  'golden-throne': { x: 74.5, y: 69 },
  'mechanism-gallery': { x: 85, y: 70 },
  'final-gate': { x: 98, y: 60 },
  'broken-vault': { x: 60, y: 92 },
  'deep-well-altar': { x: 85, y: 81 },
  'hidden-vault': { x: 85, y: 92 },
})

export const roomMapLabels = Object.freeze({
  entrance: '秘窟入口',
  'stone-court': '石门外庭',
  'old-altar': '旧祭坛',
  'broken-bridge': '断裂石桥',
  'bronze-moon-room': '铜月石室',
  'supply-alcove': '补给壁龛',
  'mechanism-path': '机关侧道',
  'stone-gate': '石门关门',
  'stone-camp': '石门营地',
  'moon-corridor': '月纹回廊',
  'moon-secret-room': '月纹密室',
  'hidden-chest-room': '隐藏宝箱',
  'sand-pit': '流沙陷坑',
  'echo-hall': '回声石厅',
  'merchant-bones': '商旅遗骨',
  'drain-path': '暗渠小径',
  'star-altar': '星纹祭台',
  'moon-gate': '月纹关门',
  'corridor-camp': '回廊营地',
  'throne-antechamber': '王座前厅',
  'star-side-hall': '星纹侧殿',
  'ancient-coffer': '古代宝匣',
  'golden-throne': '沉金王座',
  'mechanism-gallery': '机关长廊',
  'final-gate': '最终石门',
  'broken-vault': '破碎金库',
  'deep-well-altar': '深井祭坛',
  'hidden-vault': '隐秘宝库',
})

export const hintedRoomIds = Object.freeze([
  'moon-secret-room',
  'hidden-chest-room',
  'star-side-hall',
  'ancient-coffer',
])

export const visibleMapRoomIds = Object.freeze([
  'entrance',
  'stone-court',
  'old-altar',
  'broken-bridge',
  'bronze-moon-room',
  'supply-alcove',
  'mechanism-path',
  'stone-gate',
  'stone-camp',
  'moon-corridor',
  'sand-pit',
  'echo-hall',
  'merchant-bones',
  'drain-path',
  'star-altar',
  'moon-gate',
  'corridor-camp',
  'throne-antechamber',
  'golden-throne',
  'mechanism-gallery',
  'final-gate',
  'broken-vault',
  'deep-well-altar',
  'hidden-vault',
])

export const roomLabelOffsets = Object.freeze({
  entrance: { x: 0, y: 5 },
  'stone-court': { x: 0, y: 5 },
  'old-altar': { x: 0, y: -6 },
  'broken-bridge': { x: 0, y: 5 },
  'bronze-moon-room': { x: 0, y: 5 },
  'supply-alcove': { x: -2, y: 5 },
  'mechanism-path': { x: 2, y: 5 },
  'stone-gate': { x: 2, y: 5 },
  'stone-camp': { x: -2, y: 5 },
  'moon-corridor': { x: 0, y: -6 },
  'sand-pit': { x: 0, y: -6 },
  'echo-hall': { x: 0, y: -6 },
  'merchant-bones': { x: -3, y: 5 },
  'drain-path': { x: 0, y: 5 },
  'star-altar': { x: 0, y: 5 },
  'moon-gate': { x: 3, y: 5 },
  'corridor-camp': { x: 3, y: 5 },
  'throne-antechamber': { x: -2, y: -6 },
  'golden-throne': { x: 0, y: -6 },
  'mechanism-gallery': { x: 0, y: 5 },
  'final-gate': { x: -4, y: -6 },
  'broken-vault': { x: -3, y: 5 },
  'deep-well-altar': { x: 3, y: 5 },
  'hidden-vault': { x: 0, y: 5 },
})
